version: "3"

networks:
    gitea:
        external: false

services:
    gitea:
        image: gitea/gitea:1.15.0
        container_name: gitea
        restart: always
        environment:
            - USER_UID=1000
            - USER_GID=1000
            - GITEA__database__DB_TYPE=${GITEA_DB_TYPE}
            - GITEA__database__HOST=${GITEA_HOST}
            - GITEA__database__NAME=${GITEA_NAME}
            - GITEA__database__USER=${GITEA_USER}
            - GITEA__database__PASSWD=${GITEA_PASSWD}
            - DOMAIN=${GITEA_DOMAIN}
            - HTTP_PORT=${GITEA_HTTP_PORT}
            - ROOT_URL=http://${GITEA_DOMAIN}/
            - SSH_DOMAIN=${GITEA_DOMAIN}
            - VIRTUAL_HOST=${GITEA_DOMAIN}
            - VIRTUAL_PORT=${GITEA_HTTP_PORT}
        volumes:
            - ./data:/data
            - /home/git/.ssh/:/data/git/.ssh
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro
        ports:
            - "3000:3000"
            - "222:22"
            - "127.0.0.1:22:22" #SSH forwarding from the host to container
        networks:
            - gitea
        depends_on:
            - gitea-db
            - nginx-proxy

    gitea-db:
        image: postgres:13
        restart: always
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
        volumes:
            - ./postgres:/var/lib/postgresql/data
        networks:
            - gitea

    nginx-proxy:
        image: jwilder/nginx-proxy:latest
        container_name: nginx-proxy
        restart: always
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
        ports:
            - "80:80"
            - "443:443"
        privileged: true
        networks:
            - gitea
